-- Este arquivo documenta o DDL (Data Definition Language) do projeto.
-- Os comandos foram gerados automaticamente pelo Django ORM 
-- usando o comando 'manage.py sqlmigrate' para cada app.
-- Data da Geração: 2025-11-03

BEGIN;
CREATE TABLE "produto_produto" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "codigo_barras" varchar(13) NOT NULL UNIQUE,
    "nome" varchar(100) NOT NULL,
    "descricao" text NULL,
    "tipo_produto" varchar(10) NOT NULL,
    "esta_ativo" boolean NOT NULL
);
CREATE INDEX "produto_produto_codigo_barras_96799f08_like" ON "produto_produto" ("codigo_barras" varchar_pattern_ops);
COMMIT;

BEGIN;
CREATE TABLE "filial_filial" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "nome" varchar(100) NOT NULL UNIQUE,
    "cep" varchar(9) NOT NULL,
    "logradouro" varchar(255) NOT NULL,
    "cidade" varchar(100) NOT NULL,
    "estado" varchar(2) NOT NULL,
    "gerente_id" integer NULL UNIQUE,
    "esta_ativa" boolean NOT NULL
);
CREATE INDEX "filial_filial_nome_3e57d365_like" ON "filial_filial" ("nome" varchar_pattern_ops);
COMMIT;

BEGIN;
CREATE TABLE "estoque_itemestoque" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "quantidade_atual" double precision NOT NULL,
    "preco_venda_atual" numeric(10, 2) NOT NULL,
    "quantidade_minima_estoque" double precision NOT NULL,
    "filial_id" bigint NOT NULL,
    "produto_id" bigint NOT NULL
);
ALTER TABLE "estoque_itemestoque"
    ADD CONSTRAINT "estoque_itemestoque_produto_id_filial_id_7630fbe8_uniq" UNIQUE ("produto_id", "filial_id");
ALTER TABLE "estoque_itemestoque"
    ADD CONSTRAINT "estoque_itemestoque_filial_id_79fec614_fk_filial_filial_id" FOREIGN KEY ("filial_id") REFERENCES "filial_filial" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "estoque_itemestoque"
    ADD CONSTRAINT "estoque_itemestoque_produto_id_e5e9719b_fk_produto_produto_id" FOREIGN KEY ("produto_id") REFERENCES "produto_produto" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "estoque_itemestoque_filial_id_79fec614" ON "estoque_itemestoque" ("filial_id");
CREATE INDEX "estoque_itemestoque_produto_id_e5e9719b" ON "estoque_itemestoque" ("produto_id");
COMMIT;

BEGIN;
CREATE TABLE "venda_venda" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "usuario_id" integer NOT NULL,
    "data_venda" timestamp with time zone NOT NULL,
    "status" varchar(20) NOT NULL,
    "forma_pagamento" varchar(20) NULL,
    "valor_total" numeric(10, 2) NOT NULL,
    "filial_id" bigint NOT NULL
);

CREATE TABLE "venda_itemvenda" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "quantidade_vendida" double precision NOT NULL,
    "preco_vendido" numeric(10, 2) NOT NULL,
    "produto_id" bigint NOT NULL,
    "venda_id" bigint NOT NULL
);
ALTER TABLE "venda_venda"
    ADD CONSTRAINT "venda_venda_filial_id_c670b39f_fk_filial_filial_id" FOREIGN KEY ("filial_id") REFERENCES "filial_filial" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "venda_venda_filial_id_c670b39f" ON "venda_venda" ("filial_id");
ALTER TABLE "venda_itemvenda"
    ADD CONSTRAINT "venda_itemvenda_produto_id_44500338_fk_produto_produto_id" FOREIGN KEY ("produto_id") REFERENCES "produto_produto" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "venda_itemvenda"
    ADD CONSTRAINT "venda_itemvenda_venda_id_a43a6ce5_fk_venda_venda_id" FOREIGN KEY ("venda_id") REFERENCES "venda_venda" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "venda_itemvenda_produto_id_44500338" ON "venda_itemvenda" ("produto_id");
CREATE INDEX "venda_itemvenda_venda_id_a43a6ce5" ON "venda_itemvenda" ("venda_id");
COMMIT;
